### ISSUE TITLE
add redis-writer for function-replicas scaling events

### ISSUE THREAD

**Issue by jldec** [markfisher/s1p2017-faas-demo#14]
see #13 

This (additional?) redis-writer should propagate events from the `function-replicas` topic to the `demo:function-replicas` hash in redis.

key = function name 
value = replica count

**Comment by markfisher** [comment]
added: https://github.com/markfisher/s1p2017-faas-demo/blob/master/functions/redis-writer/function-replicas-writer/function-replicas-writer.yaml

also instructions in the README: https://github.com/markfisher/s1p2017-faas-demo/tree/master/functions/redis-writer

more detail will be added to the README including examples of accepted input formats, but the yaml above is already setup to accept the events on the `function-replicas` topic
