### ISSUE TITLE
fyi - redis helm chart installs redis with disabled FLUSHALL and FLUSHDB

### ISSUE THREAD

**Issue by jldec** [markfisher/s1p2017-faas-demo#19]
Comment out the following 2 lines in `redis.conf` which is stored in a PV under `/tmp/hostpath-provisioner/` on the minikube VM. e.g. using   
`sed -e "s/^rename-command/# rename-commmand" <infile >outfile`

```
rename-command FLUSHDB ""
rename-command FLUSHALL ""
```

**Comment by markfisher** [comment]
ah, glad you discovered that! `FLUSHALL` is my favorite Redis command.

**Comment by jldec** [comment]
The latest [ui README](https://github.com/markfisher/s1p2017-faas-demo/blob/master/ui/README.md) suggests installing redis in minikube without persistence in order to avoid an issue with re-using PVs. This also removes the need to flush the db occasionally.

`helm install -n counters stable/redis --set serviceType=NodePort --set persistence.enabled=false`

**Comment by markfisher** [comment]
should we also update the `install-redis` script for that?

**Comment by jldec** [comment]
good point - pushed a change
