### ISSUE TITLE
autoscaling enhancement 

### ISSUE THREAD

**Issue by jldec** [markfisher/s1p2017-faas-demo#23]
The demo would be smoother if it were easier to show more incremental scaling up and down

- scale up from 0-1, then wait for cold-start and offset to start moving, then scale 1-N if necessary
- scale down from n-1 incrementally instead of all at once, the pause scaling down at 1, before going to 0.

**Comment by markfisher** [comment]
I experimented a bit with tapered downscale delays. For example, scaling `1->0` should be the full `idleTimeout` value, but scaling `max->(max-1)` should be 1/2 of the `idleTimeout` (with the rest of the range adjusted linearly. That's just one idea; implementation could vary and will likely continue to evolve.

**Comment by markfisher** [comment]
this needs to be reported as a `function-controller` issue (those changes would be internal based on the current state)

**Comment by jldec** [comment]
Nice progress was made on scaling for the S1P demo. Ongoing effort on scaling continues. closing this issue.
