### ISSUE TITLE
memory leak in vote stream processor?

### ISSUE THREAD

**Issue by jldec** [markfisher/s1p2017-faas-demo#40]
It appears that the reactor [code](https://github.com/markfisher/s1p2017-faas-demo/blob/master/functions/vote-stream-processor/src/main/java/functions/VoteStreamProcessor.java) in the vote stream processor is running out of resources pretty quickly.  It should be possible to process moving windows without accumulating more and more data in memory. 

See attached [stream-processor-log.txt](https://github.com/markfisher/s1p2017-faas-demo/files/1612136/stream-processor-log.txt)

**Comment by markfisher** [comment]
changing from `concatMap` to `flatMap` did *not* seem to affect the accumulating state

**Comment by markfisher** [comment]
we should monitor this Reactor PR which should provide the fix: https://github.com/reactor/reactor-core/pull/1013

**Comment by markfisher** [comment]
since that PR has been merged, we should now try the demo with reactor 3.2.0.M1

**Comment by jldec** [comment]
Looks like the problem is still there - see attached [stream-processor-log-reactor-3-2-0-M1.txt](https://github.com/markfisher/s1p2017-faas-demo/files/1641267/stream-processor-log-reactor-3-2-0-M1.txt)

**Comment by jldec** [comment]
actually that deploy was using the older reactor - forgot to update the dependency in the java function invoker. stay tuned....

**Comment by jldec** [comment]
This one looks a lot better - will let it run for a while and see if it degrades like the old one.
[stream-processor-log-reactor-3-2-0-M1-take-2.txt](https://github.com/markfisher/s1p2017-faas-demo/files/1641370/stream-processor-log-reactor-3-2-0-M1-take-2.txt)

**Comment by jldec** [comment]
looks like it worked - closing
